
import openpyxl as opxl
import os   #operating sytem utility


import sys
sys.path.insert(1,'C:\\Users\\sws5\\OneDrive - National Institute of Standards and Technology (NIST)\\ctRSD simulator and documentation\\ctRSD-simulator\\ctRSD-simulator-2.0')
import ctRSD_simulator_210 as RSDs #import simulator



model = RSDs.RSD_sim() # define the model instance

# file path for ctRSD Domains List
filepath = 'C:\\Users\\sws5\\OneDrive - National Institute of Standards and Technology (NIST)\\ctRSD simulator and documentation\\ctRSD-simulator\\ctRSD-simulator-2.0\\Sequence Compiler\\ctRSD_domains_list_210.xls'

# %%
'''
###############################################################################
# Control templates

'''

O_1 = model.ctRSD_seq_compile('O{1,rbs1-2r}',filepath,Rz='R3',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_1[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_1):
            print('O_1 Matches')
    else:
        print('O_1 Doesnt match')
        print(i)
        break
    
O_2 = model.ctRSD_seq_compile('O{1,rbs1-2r}',filepath,otype=0,term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_2[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_2):
            print('O_2 Matches')
    else:
        print('O_2 Doesnt match')
        print(i)
        break
    
O_1v = model.ctRSD_seq_compile('O{1,v2r}',filepath,Rz='R3',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTAAATCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_1v[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_1v):
            print('O_1v Matches')
    else:
        print('O_1v Doesnt match')
        print(i)
        break
    
O_2v = model.ctRSD_seq_compile('O{1,v2r}',filepath,otype=0,term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTAAATCCTTTACTTCACATTCataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_2v[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_2v):
            print('O_2v Matches')
    else:
        print('O_2v Doesnt match')
        print(i)
        break
    
# %%
'''
###############################################################################
# THE riboregulators

'''

G_1 = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1):
            print('G_1 Matches')
    else:
        print('G_1 Doesnt match')
        print(i)
        break
        

G_2 = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s2u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_2[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_2):
            print('G_2 Matches')
    else:
        print('G_2 Doesnt match')
        print(i)
        break

G_3 = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACTGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_3[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_3):
            print('G_3 Matches')
    else:
        print('G_3 Doesnt match')
        print(i)
        break
    
G_4 = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s6u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_4):
            print('G_4 Matches')
    else:
        print('G_4 Doesnt match')
        print(i)
        break
    
G_5 = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s6u',eI='e06',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTCTACTTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAAGTAGAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_5[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_5):
            print('G_5 Matches')
    else:
        print('G_5 Doesnt match')
        print(i)
        break
    
G_6 = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s4u',eI='e04',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTACTTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAAGTAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_6[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_6):
            print('G_6 Matches')
    else:
        print('G_6 Doesnt match')
        print(i)
        break
    
G_7 = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,eI='e02',s='s4u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_7[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_7):
            print('G_7 Matches')
    else:
        print('G_7 Doesnt match')
        print(i)
        break
    
G_1v = model.ctRSD_seq_compile('G{u1,v2r}',filepath,s='s4u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10a',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTAAATCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAGGATTATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1v[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1v):
            print('G_1v Matches')
    else:
        print('G_1v Doesnt match')
        print(i)
        break
    
G_1s = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCTGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1s[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1s):
            print('G_1s Matches')
    else:
        print('G_1s Doesnt match')
        print(i)
        break
    
G_1h = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4o',Rz='Rh',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTTTACTGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1h[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1h):
            print('G_1h Matches')
    else:
        print('G_1h Doesnt match')
        print(i)
        break


G_1_v = model.ctRSD_seq_compile('G{v1,rbs1-2r}',filepath,s='s4',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCAGGATTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1_v[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1_v):
            print('G_1_v Matches')
    else:
        print('G_1_v Doesnt match')
        print(i)
        break

G_1_4 = model.ctRSD_seq_compile('G{u4,rbs1-2r}',filepath,s='s4',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTACTACTAAACTTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCTGATGTGTTTAGTGGTAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1_4):
            print('G_1_4 Matches')
    else:
        print('G_1_4 Doesnt match')
        print(i)
        break


G_1_T7t = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='none',term='T7t0',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttgCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1_T7t):
            print('G_1_T7t Matches')
    else:
        print('G_1_T7t Doesnt match')
        print(i)
        break
    

G_1_PPr_T7t = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='DF30ppr',term='T7t0',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAATATTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttgCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1_PPr_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1_PPr_T7t):
            print('G_1_PPr_T7t Matches')
    else:
        print('G_1_PPr_T7t Doesnt match')
        print(i)
        break
    
G_1_Thyb10 = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='PPr_scar',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAACGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_1_Thyb10[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_1_Thyb10):
            print('G_1_Thyb10 Matches')
    else:
        print('G_1_Thyb10 Doesnt match')
        print(i)
        break
    
G_5_T7t = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s6u',eI='e06',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='none',term='T7t0',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTCTACTTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAAGTAGAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttgCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_5_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_5_T7t):
            print('G_5_T7t Matches')
    else:
        print('G_5_T7t Doesnt match')
        print(i)
        break
    

G_5_PPr_T7t = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s6u',eI='e06',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='DF30ppr',term='T7t0',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTCTACTTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAAGTAGAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAATATTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttgCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_5_PPr_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_5_PPr_T7t):
            print('G_5_PPr_T7t Matches')
    else:
        print('G_5_PPr_T7t Doesnt match')
        print(i)
        break
    
G_5_Thyb10 = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s6u',eI='e06',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='PPr_scar',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTCTACTTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAAGTAGAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAACGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_5_Thyb10[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_5_Thyb10):
            print('G_5_Thyb10 Matches')
    else:
        print('G_5_Thyb10 Doesnt match')
        print(i)
        break
    
G_5a = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s6u',eI='e6a',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTATCTATTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAATAGATAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_5a[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_5a):
            print('G_5a Matches')
    else:
        print('G_5a Doesnt match')
        print(i)
        break
    
G_5a_T7t = model.ctRSD_seq_compile('G{u1e,rbs1-2r}',filepath,s='s6u',eI='e6a',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='none',term='T7t0',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTATCTATTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAATAGATAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttgCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_5a_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_5a_T7t):
            print('G_5a_T7t Matches')
    else:
        print('G_5a_T7t Doesnt match')
        print(i)
        break
    
G_6_4 = model.ctRSD_seq_compile('G{u4e,rbs1-2r}',filepath,s='s4',eI='e04',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTACTTACTACTAAACTTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCTGATGTGTTTAGTGGTAAGTAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_6_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_6_4):
            print('G_6_4 Matches')
    else:
        print('G_6_4 Doesnt match')
        print(i)
        break

G_6_4_T7t = model.ctRSD_seq_compile('G{u4e,rbs1-2r}',filepath,s='s4',eI='e04',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='none',term='T7t0',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTACTTACTACTAAACTTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCTGATGTGTTTAGTGGTAAGTAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttgCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_6_4_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_6_4_T7t):
            print('G_6_4_T7t Matches')
    else:
        print('G_6_4_T7t Doesnt match')
        print(i)
        break

U_1 = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s4u',Rz='xR3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='tDF30ppr',term='Thyb10',ds=['riboJn'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGTTAAGGCACAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAAAAAGCCCGGATAGCTCAGTCGGTAGAGCAGCGGCCGGTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAACGGCCGCGGGTCCAGGGTTCAAGTCCCTGTTCGGGCGCCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctc'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(U_1[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(U_1):
            print('U_1 Matches')
    else:
        print('U_1 Doesnt match')
        print(i)
        break

G_4w_L = model.ctRSD_seq_compile('G{u1,w2r}',filepath,s='s6u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='DF30ppr',term='T7t0')

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTAATTAACTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAGTTAATATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAATATTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttg'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_4w_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_4w_L):
            print('G_4w_L Matches')
    else:
        print('G_4w_L Doesnt match')
        print(i)
        break

G_4_L = model.ctRSD_seq_compile('G{u1,rbs1-2r}',filepath,s='s6u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='DF30ppr',term='T7t0')

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTACCTCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAGGAGGATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAATATTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttg'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_4_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_4_L):
            print('G_4_L Matches')
    else:
        print('G_4_L Doesnt match')
        print(i)
        break

G_4v_L = model.ctRSD_seq_compile('G{u1,v2r}',filepath,s='s6u',Rz='R3',cp='c06',n='THE_L',CDS='sCFP3A',rflap='DF30ppr',term='T7t0')

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACTACATCCACATACTAAATCCTTTACTTCACATTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAGAGTATGATGTTGTGAAGTGAAGGATTATATAAATGAAACAGAACAAAGAACAGTTAGTCAGTAAAGGTGAAGAATTATTTACCGGTGTTGTACCGATATTAGTCGAACTGGACGGTGACGTAAACGGACATAAGTTCTCTGTAAGTGGAGAAGGTGAAGGGGATGCCACCTACGGGAAATTGACGCTGAAATTTATTTGCACGACAGGGAAACTGCCAGTCCCCTGGCCTACTCTGGTAACCACACTTACGTGGGGGGTTCAGTGCTTTGCACGCTATCCCGACCATATGAAGCAGCACGATTTTTTCAAATCTGCGATGCCGGAGGGCTATGTGCAAGAACGGACCATTTTCTTTAAGGACGATGGTAACTATAAAACTCGCGCCGAAGTTAAATTTGAAGGTGACACTTTGGTCAACCGTATAGAACTGAAGGGGATAGATTTTAAGGAAGATGGTAATATCCTTGGTCACAAGTTGGAATACAACTACATCAGCGATAATGTATACATCACAGCCGACAAGCAAAAAAACGGTATCAAAGCAAACTTCAAAATACGTCACAACATCGAGGACGGTGGAGTCCAGCTGGCCGACCACTACCAGCAGAACACCCCAATAGGCGACGGACCTGTTCTTCTGCCAGACAACCACTACCTTTCGACTCAATCAAAGCTTTCAAAGGATCCTAACGAGAAACGGGATCATATGGTGTTGCTTGAGTTCGTTACGGCAGCTGGTATAACCTTGGGGATGGACGAACTTTACAAATAATAATATTTGCCATGTGTATGTGGGCCAATCGTGGCGTGTCGGCCTGCTTCGGCAGGCACTGGCGCCGCCCACATACTCTGATGATCCCCAATCGTAGCGTGTCGGGGTGCGCTTGCACCCACTGGCGCTGGGATCATTCATGGCAAtagcataaccccttggggcctctaaacgggtcttgaggggttttttg'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_4v_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_4v_L):
            print('G_4v_L Matches')
    else:
        print('G_4v_L Doesnt match')
        print(i)
        break
    
# %%
'''
###############################################################################
# Inputs
'''

Io = model.ctRSD_seq_compile('I{o0}',filepath,hp5='5hp',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAATCAATAACACACATAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(Io[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(Io):
            print('Io Matches')
    else:
        print('Io Doesnt match')
        print(i)
        break

IN_1 = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_1[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_1):
            print('IN_1 Matches')
    else:
        print('IN_1 Doesnt match')
        print(i)
        break

IN_2 = model.ctRSD_seq_compile('I{u1}',filepath,hp5='5hp',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCATCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_2[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_2):
            print('IN_2 Matches')
    else:
        print('IN_2 Doesnt match')
        print(i)
        break


IN_3 = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',d='d5',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAATAATCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_3[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_3):
            print('IN_3 Matches')
    else:
        print('IN_3 Doesnt match')
        print(i)
        break
    
IN_4 = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',d='d10',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACAAAATAATCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_4):
            print('IN_4 Matches')
    else:
        print('IN_4 Doesnt match')
        print(i)
        break
    
IN_5 = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',s='s2u',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCATAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_5[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_5):
            print('IN_5 Matches')
    else:
        print('IN_5 Doesnt match')
        print(i)
        break
    
IN_6 = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',s='s4u',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCATACTataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_6[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_6):
            print('IN_6 Matches')
    else:
        print('IN_6 Doesnt match')
        print(i)
        break
    
IN_7 = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',s='s6u',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCATACTCTataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_7[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_7):
            print('IN_7 Matches')
    else:
        print('IN_7 Doesnt match')
        print(i)
        break
    
IN_8 = model.ctRSD_seq_compile('I{u1ed}',filepath,hp5='5hp0',eO='e02',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATTTCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_8[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_8):
            print('IN_8 Matches')
    else:
        print('IN_8 Doesnt match')
        print(i)
        break
    
IN_9 = model.ctRSD_seq_compile('I{u1ed}',filepath,hp5='5hp0',eO='e04',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAAACTTTCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_9[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_9):
            print('IN_9 Matches')
    else:
        print('IN_9 Doesnt match')
        print(i)
        break
    
IN_10 = model.ctRSD_seq_compile('I{u1ed}',filepath,hp5='5hp0',eO='e06',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAACTACTTTCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtagctgtcaccggatgtgctttccggtctgatgagtccgtgaggacgaaacagcctcCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_10[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_10):
            print('IN_10 Matches')
    else:
        print('IN_10 Doesnt match')
        print(i)
        break    

IN_11 = model.ctRSD_seq_compile('I{v4}',filepath,hp5='5hp',term='T7t',us=['Ug'],ds=['Ud','Ue','exc'],temp_len=300)

chck_seq = 'gaagtctaacgctgctctgggctaactgtcTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACCACTAAACAATCCTCTATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGctgaaacctcaggcatttgagaagcacacgctgaaaggaggaactatatccggattggcgactgtgtacttgttataacatctgacagttaaagtcgggagaataggagccgcaatacacaatttaccgcatctagacttaactgagatattaccatagatgactatatcta'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_11[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_11):
            print('IN_11 Matches')
    else:
        print('IN_11 Doesnt match')
        print(i)
        break
    
IN_13 = model.ctRSD_seq_compile('I{v5}',filepath,hp5='5hpT',term='T7t',us=['Ug'],ds=['Ud','Ue','exc'],temp_len=300)

chck_seq = 'gaagtctaacgctgctctgggctaactgtcTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCTACCATACTACAATCCTCTATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGctgaaacctcaggcatttgagaagcacacgctgaaaggaggaactatatccggattggcgactgtgtacttgttataacatctgacagttaaagtcgggagaataggagccgcaatacacaatttaccgcatctagacttaactgagatattaccatagatgactatatcta'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_13[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_13):
            print('IN_13 Matches')
    else:
        print('IN_13 Doesnt match')
        print(i)
        break
    
IN_21 = model.ctRSD_seq_compile('I{u3}',filepath,hp5='5hp',term='T7t',us=['Ug'],ds=['Ud','Ue','exc'],temp_len=300)

chck_seq = 'gaagtctaacgctgctctgggctaactgtcTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACACATTCAATACATCACTATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGctgaaacctcaggcatttgagaagcacacgctgaaaggaggaactatatccggattggcgactgtgtacttgttataacatctgacagttaaagtcgggagaataggagccgcaatacacaatttaccgcatctagacttaactgagatattaccatagatgactatatcta'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_21[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_21):
            print('IN_21 Matches')
    else:
        print('IN_21 Doesnt match')
        print(i)
        break
    
IN_23 = model.ctRSD_seq_compile('I{u4}',filepath,hp5='5hp',term='T7t',us=['Ug'],ds=['Ud','Ue','exc'],temp_len=300)

chck_seq = 'gaagtctaacgctgctctgggctaactgtcTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACCACTAAACACATCACTATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGctgaaacctcaggcatttgagaagcacacgctgaaaggaggaactatatccggattggcgactgtgtacttgttataacatctgacagttaaagtcgggagaataggagccgcaatacacaatttaccgcatctagacttaactgagatattaccatagatgactatatcta'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_23[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_23):
            print('IN_23 Matches')
    else:
        print('IN_23 Doesnt match')
        print(i)
        break

IN_26 = model.ctRSD_seq_compile('I{v6}',filepath,hp5='5hpT',term='T7t',us=['Ug'],ds=['Ud','Ue','exc'],temp_len=300)

chck_seq = 'gaagtctaacgctgctctgggctaactgtcTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCTTTACCTTACTAATCCTCTATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGctgaaacctcaggcatttgagaagcacacgctgaaaggaggaactatatccggattggcgactgtgtacttgttataacatctgacagttaaagtcgggagaataggagccgcaatacacaatttaccgcatctagacttaactgagatattaccatagatgactatatcta'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_26[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_26):
            print('IN_26 Matches')
    else:
        print('IN_26 Doesnt match')
        print(i)
        break

IN_1_T7t = model.ctRSD_seq_compile('I{u1d}',filepath,hp5='5hp0',d='d20',term='T7tA',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAATATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_1_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_1_T7t):
            print('IN_1_T7t Matches')
    else:
        print('IN_1_T7t Doesnt match')
        print(i)
        break

IN_1_v_T7t = model.ctRSD_seq_compile('I{v1d}',filepath,hp5='5hp0',d='d20',term='T7t',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAAATCCTCTATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_1_v_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_1_v_T7t):
            print('IN_1_v_T7t Matches')
    else:
        print('IN_1_v_T7t Doesnt match')
        print(i)
        break
    
IN_1_4_T7t = model.ctRSD_seq_compile('I{u4d}',filepath,hp5='5hp0',d='d20',term='T7tA',us=['Ug','U1'],ds=['Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAAACCACTAAACACATCAATATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_1_4_T7t[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_1_4_T7t):
            print('IN_1_4_T7t Matches')
    else:
        print('IN_1_4_T7t Doesnt match')
        print(i)
        break

IN_8a = model.ctRSD_seq_compile('I{u1ed}',filepath,hp5='5hp0',eO='e2a',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAAATTCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_8a[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_8a):
            print('IN_8a Matches')
    else:
        print('IN_8a Doesnt match')
        print(i)
        break
    
IN_9a = model.ctRSD_seq_compile('I{u1ed}',filepath,hp5='5hp0',eO='e4a',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAACTATTCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_9a[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_9a):
            print('IN_9a Matches')
    else:
        print('IN_9a Doesnt match')
        print(i)
        break
    
IN_10a = model.ctRSD_seq_compile('I{u1ed}',filepath,hp5='5hp0',eO='e6a',d='d20',term='Thyb10*',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAAATCTATTCACTTCACAACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGGtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_10a[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_10a):
            print('IN_10a Matches')
    else:
        print('IN_10a Doesnt match')
        print(i)
        break  
    
    
IN_1_4 = model.ctRSD_seq_compile('I{u4d}',filepath,hp5='5hp0',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAAACCACTAAACACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_1_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_1_4):
            print('IN_1_4 Matches')
    else:
        print('IN_1_4 Doesnt match')
        print(i)
        break

IN_8_4 = model.ctRSD_seq_compile('I{u4ed}',filepath,hp5='5hp0',eO='e02',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATTACCACTAAACACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_8_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_8_4):
            print('IN_8_4 Matches')
    else:
        print('IN_8_4 Doesnt match')
        print(i)
        break
    
IN_9_4 = model.ctRSD_seq_compile('I{u4ed}',filepath,hp5='5hp0',eO='e04',d='d20',term='Thyb10',us=['Ug','U1'],ds=['riboJn','Ux'])

chck_seq = 'gaagtctaacgctgctctgggctaactgtcCATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAAACTTACCACTAAACACATCAataatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTcAACAGATAGCCGCGttcgCGCGGCtatctgttTTTTTTtAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(IN_9_4[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(IN_9_4):
            print('IN_9_4 Matches')
    else:
        print('IN_9_4 Doesnt match')
        print(i)
        break

    
# %% 
'''
###############################################################################
# Cascade templates
'''

G_11_L = model.ctRSD_seq_compile('G{v4,u1d}',filepath,L='L3',hp5='5hp',s='s4',d='d20',Rz='Rg',term='Thyb6',us=['U1'],ds=['riboJn','Ux'])

chck_seq = 'CATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAAATACTTAATACAAAATAATCACTTCACAACATCAACTACTAAACTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTTTAGTGGTTGATGTatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_11_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_11_L):
            print('G_11_L Matches')
    else:
        print('G_11_L Doesnt match')
        print(i)
        break


G_12_L = model.ctRSD_seq_compile('G{v4,u1d}',filepath,L='pHP4',hp5='5hp',s='s4',d='d20',Rz='Rg',term='Thyb6',us=['U1'],ds=['riboJn','Ux'])

chck_seq = 'CATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAAATACTTAATACAAAATAATCACTTCACAACATCAACTACTAAACTCGTCGACTTATCTCGAGTGAGATATTGTTGACGTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTTTAGTGGTTGATGTatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_12_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_12_L):
            print('G_12_L Matches')
    else:
        print('G_12_L Doesnt match')
        print(i)
        break

G_13_L = model.ctRSD_seq_compile('G{v5,u1d}',filepath,L='L',hp5='5hp',s='s4',d='d20',Rz='Rg',term='Thyb6',us=['U1'],ds=['riboJn','Ux'])

chck_seq = 'CATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTTCGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTAGTATGGTTGATGTatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_13_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_13_L):
            print('G_13_L Matches')
    else:
        print('G_13_L Doesnt match')
        print(i)
        break


G_14_L = model.ctRSD_seq_compile('G{v5,u1d}',filepath,L='pHP4',hp5='5hp',s='s4',d='d20',Rz='Rg',term='Thyb6',us=['U1'],ds=['riboJn','Ux'])

chck_seq = 'CATTACTCGCATCCATTCTCAGGCTGTCTCGTCTCGTCTCTTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTCGTCGACTTATCTCGAGTGAGATATTGTTGACGTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTAGTATGGTTGATGTatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_14_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_14_L):
            print('G_14_L Matches')
    else:
        print('G_14_L Doesnt match')
        print(i)
        break
    
G_15_L = model.ctRSD_seq_compile('G{v5,u1d}',filepath,L='L',hp5='5hp0',s='s4',d='d20',Rz='R3',term='Thyb6',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTTCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCAGGATTGTAGTATGGTTGATGTatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_15_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_15_L):
            print('G_15_L Matches')
    else:
        print('G_15_L Doesnt match')
        print(i)
        break


G_16_L = model.ctRSD_seq_compile('G{v5,u1d}',filepath,L='pHP4',hp5='5hp0',s='s4',d='d20',Rz='R3',term='Thyb6',ds=['riboJn','Ux'])

chck_seq = ''

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_16_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_16_L):
            print('G_16_L Matches')
    else:
        print('G_16_L Doesnt match')
        print(i)
        break
    
G_17_L = model.ctRSD_seq_compile('G{v5,u1d}',filepath,L='pHPR1',hp5='5hp0',s='s4',d='d20',Rz='Rg',term='Thyb6',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTCCGTGTTATCTCGTTGGAGATATTCATGGATACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTAGTATGGTTGATGTatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_17_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_17_L):
            print('G_17_L Matches')
    else:
        print('G_17_L Doesnt match')
        print(i)
        break

G_18_L = model.ctRSD_seq_compile('G{v5,u3d}',filepath,L='L3',hp5='5hp',s='s4',d='d20',Rz='Rg',term='Thyb6i',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAAATACTTAATACAAAATAACACATTCAATACATCAACTATACTACTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTAGTATGGTTGATGTttatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_18_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_18_L):
            print('G_18_L Matches')
    else:
        print('G_18_L Doesnt match')
        print(i)
        break


G_19_L = model.ctRSD_seq_compile('G{v5,u3d}',filepath,L='pHP4',hp5='5hp',s='s4',d='d20',Rz='Rg',term='Thyb6i',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAAATACTTAATACAAAATAACACATTCAATACATCAACTATACTACTCGTCGACTTATCTCGAGTGAGATATTGTTGACGTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAATCAGGATTGTAGTATGGTTGATGTttatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_19_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_19_L):
            print('G_19_L Matches')
    else:
        print('G_19_L Doesnt match')
        print(i)
        break
    
    
G_20_L = model.ctRSD_seq_compile('G{v4,u1d}',filepath,invert=1,L='L5',hp5='5hp0',s='s4',d='d20',Rz='Rg',term='Thyb6i',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAATCAGGATTGTTTAGTGGTTGATGTATCGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAAAATACTTAATACAAAATAATCACTTCACAACATCAACTACTAAACttatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_20_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_20_L):
            print('G_20_L Matches')
    else:
        print('G_20_L Doesnt match')
        print(i)
        break


G_21_L = model.ctRSD_seq_compile('G{u3,v4}',filepath,L='L',hp5='5hp',s='s4o',Rz='Rh',term='Thyb1',ds=['plmJn','U2'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACCACTAAACAATCCTCATATTCAATTTCGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTTTACTGATGTATTGAATGTGAGGATTatatcAAACAGATAGGCCCTCttcgGAGGGCCtatctgttTTTTTTTAGTCATAAGTCTGGGCTAAGCCCACTGATGAGTCGCTGAAATGCGACGAAACTTATGACCCTCGCTGGGAGTTCGTAGACGGAAACAAACGCAGAATCCAAGC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_21_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_21_L):
            print('G_21_L Matches')
    else:
        print('G_21_L Doesnt match')
        print(i)
        break
    
G_22_L = model.ctRSD_seq_compile('G{u3,v4}',filepath,L='pHP14',hp5='5hp',s='s4o',Rz='Rh',term='Thyb1',ds=['plmJn','U2'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACCACTAAACAATCCTCATATTCAATTCGTCGACTCTCGAGTGAGATTGTTGACGTACGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTTTACTGATGTATTGAATGTGAGGATTatatcAAACAGATAGGCCCTCttcgGAGGGCCtatctgttTTTTTTTAGTCATAAGTCTGGGCTAAGCCCACTGATGAGTCGCTGAAATGCGACGAAACTTATGACCCTCGCTGGGAGTTCGTAGACGGAAACAAACGCAGAATCCAAGC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_22_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_22_L):
            print('G_22_L Matches')
    else:
        print('G_22_L Doesnt match')
        print(i)
        break

G_23_L = model.ctRSD_seq_compile('G{u4,v5}',filepath,L='L',hp5='5hp',s='s4o',Rz='Rh',term='Thyb1',ds=['plmJn','U2'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACCATACTACAATCCTACTACTAAACTTCGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTTTACTGATGTGTTTAGTGGTAGGATTatatcAAACAGATAGGCCCTCttcgGAGGGCCtatctgttTTTTTTTAGTCATAAGTCTGGGCTAAGCCCACTGATGAGTCGCTGAAATGCGACGAAACTTATGACCCTCGCTGGGAGTTCGTAGACGGAAACAAACGCAGAATCCAAGC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_23_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_23_L):
            print('G_23_L Matches')
    else:
        print('G_23_L Doesnt match')
        print(i)
        break
    
G_24_L = model.ctRSD_seq_compile('G{u4,v5}',filepath,L='pHP14',hp5='5hp',s='s4o',Rz='Rh',term='Thyb1',ds=['plmJn','U2'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAACCATACTACAATCCTACTACTAAACTCGTCGACTCTCGAGTGAGATTGTTGACGTACGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTTTACTGATGTGTTTAGTGGTAGGATTatatcAAACAGATAGGCCCTCttcgGAGGGCCtatctgttTTTTTTTAGTCATAAGTCTGGGCTAAGCCCACTGATGAGTCGCTGAAATGCGACGAAACTTATGACCCTCGCTGGGAGTTCGTAGACGGAAACAAACGCAGAATCCAAGC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_24_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_24_L):
            print('G_24_L Matches')
    else:
        print('G_24_L Doesnt match')
        print(i)
        break
    
G_25_L = model.ctRSD_seq_compile('G{u3,v4}',filepath,invert=1,L='L5',hp5='5hp0',s='s4o',Rz='Rh',term='Thyb1i',ds=['plmJn','U2'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCTTACTGATGTATTGAATGTGAGGATTATCGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTAACCACTAAACAATCCTCATATTCAATttaacAAACAGATAGGCCCTCttcgGAGGGCCtatctgttTTTTTTTAGTCATAAGTCTGGGCTAAGCCCACTGATGAGTCGCTGAAATGCGACGAAACTTATGACCCTCGCTGGGAGTTCGTAGACGGAAACAAACGCAGAATCCAAGC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_25_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_25_L):
            print('G_25_L Matches')
    else:
        print('G_25_L Doesnt match')
        print(i)
        break
    
G_26_L = model.ctRSD_seq_compile('G{v6,u3}',filepath,L='L3',hp5='5hp',s='s4',Rz='R3',term='Thyb3i',ds=['sarJn','U3','exc'],temp_len=300)

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACACATTCAATACATCATTATCTTACTTACGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCAGGATTAGTAAGGTAATGATGTttatcAACAGATAGGCCGCttcgGCGGCCtatctgttTTTTTTAGACTGTCGCCGGATGTGTATCCGACCTGACGATGGCCCAAAAGGGCCGAAACAGTCCTCGCACTGAAGGTCCTCAATCGCACTGGAAACATCAAGGTCGa'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_26_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_26_L):
            print('G_26_L Matches')
    else:
        print('G_26_L Doesnt match')
        print(i)
        break
    
G_27_L = model.ctRSD_seq_compile('G{v6,u3}',filepath,L='pHPR1t',hp5='5hp',s='s4',Rz='R3',term='Thyb3i',ds=['sarJn','U3'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCACACATTCAATACATCATTATCTTACTTTCCGTGTTATCTCGTTGGAGATATTCATGGATACGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAATCAGGATTAGTAAGGTAATGATGTttatcAACAGATAGGCCGCttcgGCGGCCtatctgttTTTTTTAGACTGTCGCCGGATGTGTATCCGACCTGACGATGGCCCAAAAGGGCCGAAACAGTCCTCGCACTGAAGGTCCTCAATCGCACTGGAAACATCAAGGTCG'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_27_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_27_L):
            print('G_27_L Matches')
    else:
        print('G_27_L Doesnt match')
        print(i)
        break
    
G_28_L = model.ctRSD_seq_compile('G{v6,u3}',filepath,invert=1,L='L3',hp5='5hp0',s='s4',Rz='R3',term='Thyb3ia',ds=['sarJn','U3','exc'],temp_len=300)

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAATCAGGATTAGTAAGGTAATGATGTTACGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACACACATTCAATACATCATTATCTTACTttaacAACAGATAGGCCGCttcgGCGGCCtatctgttTTTTTTAGACTGTCGCCGGATGTGTATCCGACCTGACGATGGCCCAAAAGGGCCGAAACAGTCCTCGCACTGAAGGTCCTCAATCGCACTGGAAACATCAAGGTCGa'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_28_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_28_L):
            print('G_28_L Matches')
    else:
        print('G_28_L Doesnt match')
        print(i)
        break

G_29_L = model.ctRSD_seq_compile('G{v5,u1d}',filepath,invert=1,L='L5',hp5='5hp0',s='s4',d='d20',Rz='Rg',term='Thyb6i',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAATCAGGATTGTAGTATGGTTGATGTATCGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACttatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_29_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_29_L):
            print('G_29_L Matches')
    else:
        print('G_29_L Doesnt match')
        print(i)
        break


G_30_L = model.ctRSD_seq_compile('G{u4,v5}',filepath,invert=1,L='L5',hp5='5hp0',s='s4o',Rz='Rh',term='Thyb1i',ds=['plmJn','U2'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCTTACTGATGTGTTTAGTGGTAGGATTATCGGGGGCCACAGCAGAAGCGTTCACGTCGCAGCCCCTGTCAGATTCTGGTGAATCTGCGAATTCTGCTAACCATACTACAATCCTACTACTAAACttaacAAACAGATAGGCCCTCttcgGAGGGCCtatctgttTTTTTTTAGTCATAAGTCTGGGCTAAGCCCACTGATGAGTCGCTGAAATGCGACGAAACTTATGACCCTCGCTGGGAGTTCGTAGACGGAAACAAACGCAGAATCCAAGC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_30_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_30_L):
            print('G_30_L Matches')
    else:
        print('G_30_L Doesnt match')
        print(i)
        break

G_31_L = model.ctRSD_seq_compile('G{v6,u4}',filepath,invert=1,L='L5',hp5='5hp0',s='s4',Rz='R3',term='Thyb3ia',ds=['sarJn','U3','exc'],temp_len=300)

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAATCAGGATTAGTAAGGTAATGATGTATCGGGTCGGCATGGCATGTGCACCTCCTCGCGGTCCGACCTGGGCTACTTCGGTAGGCTAAGGCACAACCACTAAACACATCATTATCTTACTttaacAACAGATAGGCCGCttcgGCGGCCtatctgttTTTTTTAGACTGTCGCCGGATGTGTATCCGACCTGACGATGGCCCAAAAGGGCCGAAACAGTCCTCGCACTGAAGGTCCTCAATCGCACTGGAAACATCAAGGTCGa'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(G_31_L[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(G_31_L):
            print('G_31_L Matches')
    else:
        print('G_31_L Doesnt match')
        print(i)
        break



O_13 = model.ctRSD_seq_compile('O{5,u1d}',filepath,hp5='5hp0',L='L3',d='d20',Rz='Rg',term='Thyb6',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_13[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_13):
            print('O_13 Matches')
    else:
        print('O_13 Doesnt match')
        print(i)
        break
    
O_14 = model.ctRSD_seq_compile('O{5,u1d}',filepath,hp5='5hp0',d='d20',L='pHP4',Rz='Rg',term='Thyb6',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTCGTCGACTTATCTCGAGTGAGATATTGTTGACGTACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_14[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_14):
            print('O_14 Matches')
    else:
        print('O_14 Doesnt match')
        print(i)
        break
    
O_15 = model.ctRSD_seq_compile('O{5,u1d}',filepath,hp5='5hp0',d='d20',L='pHPR1',Rz='Rg',term='Thyb6',ds=['riboJn','Ux'])

chck_seq = 'TTCTAATACGACTCACTATAGGGAGATTCGTCTCCCAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACTCCGTGTTATCTCGTTGGAGATATTCATGGATACGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACC'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_15[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_15):
            print('O_15 Matches')
    else:
        print('O_15 Doesnt match')
        print(i)
        break

O_16 = model.ctRSD_seq_compile('O{5,u1d}',filepath,invert=1,hp5='ldr4',L='none',d='d20',Rz='Rg',term='Thyb6',ds=['riboJn','Ux','exc'],temp_len=300)

chck_seq = 'TTCTAATACGACTCACTATAGGGAGGCCGGCATGGTCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGACAAAATACTTAATACAAAATAATCACTTCACAACATCAACTATACTACatatcAGATAACAGATACttcgGtatctgttatctgttTTTTTTAGCTGTCACCGGATGTGCTTTCCGGTCTGATGAGTCCGTGAGGACGAAACAGCCTCCCAGGATACATAGATTACCACAACTCCGAGCCCTTCCACCactgt'

for i in range(len(chck_seq)):
    if str.lower(chck_seq[i]) == str.lower(O_16[i]):
        if i+1 == len(chck_seq) and len(chck_seq)==len(O_16):
            print('O_16 Matches')
    else:
        print('O_16 Doesnt match')
        print(i)
        break